# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: edgeowner
subtitle: 多读书，读好书，少写bug
description: Summer和Sunny博客乐园
author:  ZhangSunny
language: zh-Hans
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://edgeowner.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: 
  - 'av-core-mini-0.6.4.js'
  
# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 6
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

archive_generator: 
  per_page: 10 ##归档页面默认20篇文章标题
  yearly: true  ##生成年视图
  monthly: true ##生成月视图

tag_generator:
  per_page: 10

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
# per_page: 10
# pagination_dir: page






# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment repository: git@github.com:Name/Name.github.io.git
## Docs: https://hexo.io/docs/deployment.html
#https://git.coding.net/zhangsunny/blog.git
#https://git.coding.net/zhangsunny/blog.git
#https://git.coding.net/zhangsunny/blogs.git
deploy:
  type: git
  repository:
      github: git@github.com:edgeowner/edgeowner.github.io.git
      # 增加这一行
      coding: git@git.coding.net:zhangsunny/blogs.git
  branch: master


#deploy:
  #type: git
  #repo: 
    #git: git@106.14.148.54/home/git/hexo.git,master



#algolia: 
  #applicationID: 62TBHZV7K0
  #apiKey: b9631b740708ee1be06f434de2d5fc49
  #indexName: blogs
  #chunkSize: 5000
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# 自动生成sitemap
sitemap: 
  path: sitemap.xml
baidusitemap: 
  path: baidusitemap.xml

baidu_url_submit:
  count: 100 # 提交最新的一个链接
  host: edgeowner.com # 在百度站长平台中注册的域名
  token: XUTRTvTLzLQRnYAn # 请注意这是您的秘钥， 所以请不要把博客源代码发布在公众仓库里!
  path: baidu_urls.txt # 文本文档的地址， 新链接会保存在此文本文档里


google_site_verification: google95784a9a78d968a0
baidu-site-verification: c7GpAJhSvl