
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `company_id` bigint(20) DEFAULT NULL COMMENT '公司id',
  `merchant_product_id` bigint(20) NOT NULL COMMENT '商品ID',
  `type` int(11) DEFAULT '0' COMMENT '文描类型 PC=1 ，手机=0',
  `content` text COMMENT '富文本内容',
  `is_deleted` int(11) DEFAULT NULL COMMENT '是否逻辑删除:默认0未删除;1已删除',
  `is_available` int(11) DEFAULT NULL COMMENT '是否可用:默认0否;1是',
  `server_ip` varchar(60) DEFAULT NULL COMMENT '服务器IP',
  `version_no` int(11) DEFAULT NULL COMMENT '版本号:默认0,每次更新+1',
  `client_versionno` varchar(40) DEFAULT NULL COMMENT '客户端程序的版本号',
  `create_username` varchar(100) DEFAULT NULL COMMENT '创建人姓名',
  `update_username` varchar(100) DEFAULT NULL COMMENT '最后修改人姓名',
  `create_time` timestamp NULL DEFAULT NULL COMMENT '创建时间-应用操作时间',
  `update_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `create_usermac` varchar(60) DEFAULT NULL COMMENT '创建人MAC地址',
  `update_usermac` varchar(60) DEFAULT NULL COMMENT '最后修改人MAC',
  `create_userid` bigint(20) DEFAULT NULL COMMENT '创建人ID',
  `update_userid` bigint(20) DEFAULT NULL COMMENT '最后修改人ID',
  `create_userip` varchar(60) DEFAULT NULL COMMENT '创建人IP',
  `update_userip` varchar(60) DEFAULT NULL COMMENT '最后修改人IP',
  `create_time_db` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间-数据库操作时间',
  `update_time_db` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最后修改时间-数据库默认写入时间',
